config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'room_generator#home'
  get '/create', to: 'room_generator#create'
  post '/update_amenity', to: 'room_generator#update_amenity'
  post '/save_room', to: 'room_generator#save_room'
  get '/washroom/:name', to: 'room_manager#show', as: 'get_washroom'
  put '/washroom/:name', to: 'room_manager#update_amenity'

end

app/models/amenity.rb
class Amenity < ApplicationRecord
  belongs_to :washroom
  default_scope -> { order(created_at: :desc) }
  validates :position, presence: true
  validates :status, presence: true
  serialize :position
  before_save {
    if (status)
      status.downcase!
    end
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/washroom.rb
# == Schema Information
#
# Table name: washrooms
#
#  name                :string(255)
#  grid                :text [array]

class Washroom < ApplicationRecord
  validates :grid, presence: true
  validates :name, length: { maximum: 30 }
  validates :password, length: { maximum: 140 }
  serialize :grid

  before_save {
    if (self.name)
      self.name.downcase!
    end
  }
  has_many :amenities, class_name: "Amenity", dependent: :destroy

  def getAmenityStatus(xCoor, yCoor)
    amenity = amenities.find_by_position([xCoor, yCoor])
    if (amenity && !amenity.status.casecmp?("None"))
      amenity.status.titleize
    else
      ""
    end
  end

  def hasAmenity(xCoor, yCoor)
    !!amenities.find_by_position([xCoor, yCoor])
  end

  def getAmenityName(xCoor, yCoor)
    amenity = amenities.find_by_position([xCoor, yCoor])
    if (amenity)
      amenity.name
    else
      ""
    end
  end

  def addAmenity(params)
    amenity = amenities.find_by_position([params[:xCoor].to_i, params[:yCoor].to_i])
    if (amenity)
      amenity.update(position: [params[:xCoor].to_i, params[:yCoor].to_i], name: params[:name], status: params[:status])
    else
      amenities << Amenity.new(position: [params[:xCoor].to_i, params[:yCoor].to_i], name: params[:name], status: params[:status])
    end
  end

  def removeAmenity(params)
    #Remove key value at amenity hash position
    amenity = amenities.find_by_position([params[:xCoor].to_i, params[:yCoor].to_i])
    if (amenity)
      amenity.destroy
    end
  end

  def updateAmenity(name, status)
    #Update status of amenity,
    amenity = amenities.find_by_name(name)
    amenity.update(status: status)
  end

  def getColorForPosition(position)
    amenity = amenities.find_by_position(position)
    if (amenity)
      getColorByStatus(amenity.status)
    else
      puts "no status"
      "white"
    end
  end

  def getColorByStatus(status)
    if status.casecmp?("None")
      "black"
    elsif status.casecmp?("Vacant")
      "green"
    elsif status.casecmp?("In Use")
      "red"
    elsif status.casecmp?("Out of Service")
      "orange"
    else
      "white"
    end
  end

  def get_amenity_color(position)
    getColorForPosition(position)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/room_generator_controller.rb
class RoomGeneratorController < ApplicationController

  helper_method :get_amenity_color
  before_action :get_washroom

  def get_washroom
    if session[:washroom_id]
      @washroom = Washroom.find(session[:washroom_id])
    else
      @washroom = Washroom.create(grid: [5, 11])
      @washroom.save
      session[:washroom_id] = @washroom.id
    end
  end

  def home
  end

  def create
  end

  def save_room
    Rails.logger.info("PARAMS: #{params.inspect}")
    @name_error = nil
    @password_error = nil
    puts params[:name]
    if params[:name] && (Washroom.find_by_name(params[:name]))
      @name_error = "This name has been taken"
    elsif params[:name].nil? || params[:name].empty?
      @name_error = "Name is invalid"
    end
    puts params[:password]
    if params[:password].nil? || params[:password].empty?
      @password_error = "Invalid password"
    end
    if @name_error || @password_error
      respond_to do |format|
        format.js
      end
      return
    end
    @washroom.name = params[:name]
    @washroom.password = params[:password]
    @washroom.save
    redirect_to get_washroom_path(params[:name])
    #Todo reroute to show screen and delete current cache
  end

  def update_amenity
    if params[:commit] == "Delete"
      @washroom.removeAmenity(params)
      @color = "white"
    elsif params[:commit] == "Submit"
      @washroom.addAmenity(params)
      @color = @washroom.getColorByStatus(params[:status])
    end
    @xCoord = params[:xCoor].to_i
    @yCoord = params[:yCoor].to_i
    # Todo update screen with new data
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/room_manager_controller.rb
class RoomManagerController < ApplicationController
  protect_from_forgery except: :update_amenity
  @@STATUS_LIST = ["out of service", "vacant", "in use"]

  def show()
    #todo add logic to show that not found and redirect to creation
    get_washroom_by_name(params[:name])
  end

  def update_amenity()
    get_washroom_by_name(params[:name])
    if (params[:password] != @washroom.password)
      render json: { errors: 'Invalid password' }, status: 403
      return
    end
    validStatus = get_valid_status(params[:status])
    if (validStatus)
      @washroom.updateAmenity(params[:amenity_name], params[:status].downcase!)
      return
    else
      render json: { errors: 'Invalid status' }, status: 400
    end
  end

  private

  def get_washroom_by_name(name)
    @washroom = Washroom.find_by_name(name)
  end

  def get_valid_status(status)
    @@STATUS_LIST.include? status.downcase!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def status_options
    ["None", "Vacant", "In Use", "Out of Service"]
  end
end

app/helpers/room_generator_helper.rb
module RoomGeneratorHelper
end

app/helpers/room_manager_helper.rb
module RoomManagerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WashRoomStatus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/room_generator/create.html.erb
<div class="container-fluid">
  <% for @x in 0..@washroom.grid[0] do %>
    <div class="row">
        <% for @y in 0..@washroom.grid[1] do %>
          <% if @washroom.hasAmenity(@x, @y) %>
            <div class="col-md-1 btn" data-toggle="modal" style="background-color: <%= @washroom.get_amenity_color([@x, @y]) %>" id=<%="#{@x}#{@y}"%> data-target=<%="#modal#{@x}#{@y}"%>>
          <% else %>
            <div class="col-md-1 btn" data-toggle="modal" id=<%="#{@x}#{@y}"%> data-target=<%="#modal#{@x}#{@y}"%>>
          <% end %>
            <h4 id=<%="#{@x}#{@y}text"%> ><%= @washroom.getAmenityName(@x, @y) %></h4>
          </div>
          <div class="modal fade" title="amenity_modal" id=<%="modal#{@x}#{@y}"%>>
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
                  <h3 id="myModalLabel">Add an amenity</h3>
                </div>
                <div class="modal-body">
                  <!-- This action points to /update_amenity in routes-->
                  <form action="update_amenity" method="post" data-remote="true">
                    <div hidden class="form-group">
                      <input type="number" name="xCoor" value=<%="#{@x}"%>>
                    </div>
                    <div hidden class="form-group">
                      <input type="number" name="yCoor" value=<%="#{@y}"%>>
                    </div>
                    <div class="form-group">
                      <label for="name">Name:</label>
                      <input type="text" name="name" value="<%=@washroom.getAmenityName(@x, @y)%>" class="form-control" id="name" placeholder="Optional">
                    </div>
                    <div class="form-group">
                      <label for="status">Status</label>
                      <select name="status" class="form-control" id=status>
                        <% if @washroom.hasAmenity(@x, @y) %>
                          <option selected hidden><%=@washroom.getAmenityStatus(@x, @y)%></option>
                        <% end %>
                        <option>None</option>
                        <option>Vacant</option>
                        <option>In Use</option>
                        <option>Out of Service</option>
                      </select>
                    </div>
                    <input value="Submit" type="submit" class="btn btn-default" name="commit"/>
                    <input value="Delete" type="submit" class="btn btn-default" name="commit"/>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  <% end %>
  <%= link_to 'Save', '#', data: {toggle: "modal", target: "#save_modal"}, :class => "btn create_button" %>
  <!-- <%= button_to 'Save', {data: {toggle: "modal", target: "#save_modal"}, remote: true}, {class: 'btn create_button'} %> -->
  <div class="modal fade" title="save_modal" id="save_modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
          <h3 id="myModalLabel">Save Room</h3>
        </div>
        <div class="modal-body">
          <!-- This action points to /update_amenity in routes-->
          <form action="save_room" method="post" data-remote="true">
            <div class="form-group" id="save_name">
              <label for="name">Name:</label>
              <input type="text" name="name" class="form-control" id="name" placeholder="Required">
              <small id="name_error" class="text-danger">
              </small>
            </div>
            <div class="form-group" id="save_password">
              <label for="password">Password:</label>
              <input type="text" name="password" class="form-control" id="password" placeholder="Required">
              <small id="password_error" class="text-danger">
              </small>
            </div>
            <input value="Save" type="submit" class="btn btn-default" name="commit"/>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/room_generator/home.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<div class = "container">
  <h1>Room Generator</h1>
  <p>Create a grid layout of a room and manage the status's of amenities within the room</p>
  <%= button_to 'Create a room', create_path, method: :get, class: 'button' %>
</div>

app/views/room_generator/save_room.js.erb
$("#name_error").text("<%=@name_error%>")
$("#password_error").text("<%=@password_error%>")

app/views/room_generator/update_amenity.js.erb
$("#modal<%=@xCoord%><%=@yCoord%>").modal("toggle");
$("#<%=@xCoord%><%=@yCoord%>").css('background-color', "<%=@color%>")
$("#<%=@xCoord%><%=@yCoord%>text").text("<%=@washroom.getAmenityName(@xCoord, @yCoord)%>")

app/views/room_manager/show.html.erb
<div class="container-fluid">
  <div class="row">
    <ul class="legend">
      <li><span class="vacant" style="background-color: green"><p>Vacant</p></span></li>
      <li><span class="in_use" style="background-color: red"><p>In Use</p></span></li>
      <li><span class="out_of_order" style="background-color: orange"><p>Out of Order</p></span></li>
    </ul>
  </div>
  <% for @x in 0..@washroom.grid[0] do %>
    <div class="row">
        <% for @y in 0..@washroom.grid[1] do %>
          <div class="col-md-1 btn" style="background-color: <%= @washroom.get_amenity_color([@x, @y]) %>" id=<%="#{@x}#{@y}"%>
            <h4 id=<%="#{@x}#{@y}text"%> ><%= @washroom.getAmenityName(@x, @y) %></h4>
          </div>
        <% end %>
    </div>
  <% end %>
</div>